import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Stitch Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?display=swap&family=Noto+Sans:wght@400;500;700;900&family=Spline+Sans:wght@400;500;700" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="icon" href="data:image/x-icon;base64," type="image/x-icon"/>
      </head>
      <body
        className="bg-background text-text-primary"
      >
        <div className="relative flex size-full min-h-screen flex-col group/design-root overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
