version: '3.8'

services:
  backend:
    build: backend
    container_name: python-backend
    ports:
      - "8080:5000"
  frontend:
    build: frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend